name: Build Release Binaries

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4

      - name: Install QEMU
        if: matrix.target != 'x86_64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }}
          # Strip binaries to reduce size
          strip target/${{ matrix.target }}/release/moblink-relay
          strip target/${{ matrix.target }}/release/moblink-relay-service
          strip target/${{ matrix.target }}/release/moblink-streamer
          # Rename binaries to include target
          mv target/${{ matrix.target }}/release/moblink-relay target/${{ matrix.target }}/release/moblink-relay-${{ matrix.target }}
          mv target/${{ matrix.target }}/release/moblink-relay-service target/${{ matrix.target }}/release/moblink-relay-service-${{ matrix.target }}
          mv target/${{ matrix.target }}/release/moblink-streamer target/${{ matrix.target }}/release/moblink-streamer-${{ matrix.target }}
          ls -la target/${{ matrix.target }}/release/

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/${{ matrix.target }}/release/moblink-relay-${{ matrix.target }}
            target/${{ matrix.target }}/release/moblink-relay-service-${{ matrix.target }}
            target/${{ matrix.target }}/release/moblink-streamer-${{ matrix.target }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Binaries for ${{ github.ref_name }}

            ### Binaries included:
            - moblink-relay
            - moblink-relay-service
            - moblink-streamer

            ### Architectures:
            - x86_64 (GNU)
            - ARM (32-bit, hard-float)
            - ARM64 (GNU)
